#!/bin/bash

grepflag=off
replaceflag=off
cleanbkpflag=off
grepstring=
replacepattern=

while getopts g:r:c opt
do
    case "$opt" in
      g)  grepflag=on; grepstring="$OPTARG";;
      r)  replaceflag=on; replacepattern="$OPTARG";;
      c)  cleanbkpflag=on;;
      \?)		# unknown flag
      	  echo >&2 \
	  "usage: $0 [[-g \"string_to_grep\"]|[-r \"replace_pattern\"]|[-c]]"
	  exit 1;;
    esac
done
shift `expr $OPTIND - 1`

#replacepattern="'"$replacepattern"'"

if [ $grepflag == on ]
then

	find . -type f ! -name "*.lat.bkp" ! -name "*.jpg" ! -name "*.png" ! -name "*.gif" ! -name "*.JPG" ! -name "*.PNG" ! -name "*.GIF" ! -name "*.swf" ! -name "*.zip" ! -name "*.mp3" ! -path "*.svn*" ! -path "*.git" | xargs file | grep "text" | awk -F: '{print $1}' | xargs grep -n -- "$grepstring" | gawk 'match($0, /^(.*):([0-9]+): *(.*)$/, m) { if (m[1] != last_file) { marcador = "\n====================================================================\n"; print marcador m[1] marcador; } print "#" m[2] ": " m[3] "\n"; last_file = m[1] }'

else

	if [ $cleanbkpflag == on ]
	then
		find . -type f -name "*.lat.bkp" | xargs rm
	else
		if [ $replaceflag == on ]
		then
			find . -type f ! -name "*.jpg" ! -name "*.png" ! -name "*.gif" ! -name "*.JPG" ! -name "*.PNG" ! -name "*.GIF" ! -name "*.swf" ! -name "*.zip" ! -name "*.mp3" ! -path "*.svn*" | xargs file | grep "text" | awk -F: '{print $1}' | xargs sed -i.lat.bkp -e "$replacepattern"	
		else
			find . -type f ! -name "*.jpg" ! -name "*.png" ! -name "*.gif" ! -name "*.JPG" ! -name "*.PNG" ! -name "*.GIF" ! -name "*.swf" ! -name "*.zip" ! -name "*.mp3" ! -path "*.svn*" | xargs file | grep "text" | awk -F: '{print $1}'
		fi
	fi
	
fi


